import postgres from 'postgres';
import * as dotenv from 'dotenv';
dotenv.config();
const sql = postgres(process.env.DATABASE_URL!);
await sql`ALTER TABLE segments ADD COLUMN IF NOT EXISTS transit_legs text`;
await sql`ALTER TABLE segments ADD COLUMN IF NOT EXISTS walk_to_station_min double precision`;
await sql`ALTER TABLE segments ADD COLUMN IF NOT EXISTS walk_from_station_min double precision`;
await sql`ALTER TABLE segments ADD COLUMN IF NOT EXISTS transfers integer`;
await sql`ALTER TABLE segments ADD COLUMN IF NOT EXISTS walk_geometry text`;
await sql`ALTER TABLE segments ADD COLUMN IF NOT EXISTS drive_geometry text`;
await sql`ALTER TABLE segments ADD COLUMN IF NOT EXISTS transit_geometry text`;
console.log('Added segment columns');
await sql.end();
